name: Builds

on: [push, pull_request]

jobs:
  Windows:
    name: Windows latest
    runs-on: windows-latest 
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build
      run: nmake
